# From https://github.com/marketplace/actions/buildozer-action
name: Build

on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Android SDK and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          mkdir -p "$ANDROID_HOME" && cd "$ANDROID_HOME"
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
          unzip -o cmdline-tools.zip -d cmdline-tools
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-28" "build-tools;28.0.3" "platform-tools"
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/bin:$PATH

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython kivy buildozer

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: android debug
          buildozer_version: stable
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          PATH: ${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/cmdline-tools/bin:${{ github.workspace }}/android-sdk/build-tools/28.0.3:$PATH

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
