name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Git and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget unzip
          git --version
          which git

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Android SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT
          cd $ANDROID_SDK_ROOT
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest && mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          yes | cmdline-tools/latest/bin/sdkmanager --licenses
          yes | cmdline-tools/latest/bin/sdkmanager --update
          yes | cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;30.0.3" "ndk;21.1.6352462"
        env:
          ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk

      - name: Ensure build-tools and aidl are installed
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --list
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall "build-tools;35.0.0"
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "build-tools;30.0.3"
          ls ${ANDROID_SDK_ROOT}/build-tools/30.0.3/
          if [ ! -f "${ANDROID_SDK_ROOT}/build-tools/30.0.3/aidl" ]; then
            echo "aidl not found in build-tools;30.0.3, trying build-tools;31.0.0"
            ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "build-tools;31.0.0"
            ls ${ANDROID_SDK_ROOT}/build-tools/31.0.0/
          fi
        env:
          ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython kivy buildozer

      - name: Build with Buildozer
        run: |
          export PATH=${{ runner.tool_cache }}/android-sdk/build-tools/30.0.3:${PATH}
          buildozer android debug
        env:
          ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk
          ANDROID_NDK_HOME: ${{ runner.tool_cache }}/android-sdk/ndk/21.1.6352462
          GIT: /usr/bin/git
          PATH: /usr/bin:${{ runner.tool_cache }}/android-sdk/platform-tools:${{ runner.tool_cache }}/android-sdk/cmdline-tools/latest/bin:${{ runner.tool_cache }}/android-sdk/build-tools/30.0.3:${{ runner.tool_cache }}/android-sdk/build-tools/31.0.0:$PATH

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
