# From https://github.com/marketplace/actions/buildozer-action
name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker container
        run: |
          docker run --name buildozer-container -d -v ${{ github.workspace }}:/workspace -w /workspace python:3.9-slim tail -f /dev/null

      - name: Install dependencies
        run: |
          docker exec buildozer-container sh -c "apt-get update && apt-get install -y openjdk-11-jdk wget unzip"
          docker exec buildozer-container sh -c "mkdir -p /root/.android && touch /root/.android/repositories.cfg"
          docker exec buildozer-container sh -c "wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O commandlinetools.zip"
          docker exec buildozer-container sh -c "unzip commandlinetools.zip -d /usr/local/android-sdk/cmdline-tools"
          docker exec buildozer-container sh -c "mv /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest"
          docker exec buildozer-container sh -c "yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses"
          docker exec buildozer-container sh -c "yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --update"
          docker exec buildozer-container sh -c "/usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager 'platform-tools' 'platforms;android-31' 'build-tools;31.0.0' 'ndk;21.1.6352462'"
        env:
          ANDROID_SDK_ROOT: /usr/local/android-sdk

      - name: Install Python dependencies
        run: |
          docker exec buildozer-container sh -c "pip install --upgrade pip"
          docker exec buildozer-container sh -c "pip install cython kivy buildozer"

      - name: Build with Buildozer
        run: |
          docker exec buildozer-container sh -c "buildozer android debug"
        env:
          ANDROID_SDK_ROOT: /usr/local/android-sdk
          ANDROID_NDK_HOME: /usr/local/android-sdk/ndk/21.1.6352462
          PATH: /usr/local/android-sdk/platform-tools:/usr/local/android-sdk/cmdline-tools/latest/bin:/usr/local/android-sdk/build-tools/31.0.0:$PATH

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk

      - name: Cleanup Docker container
        run: docker rm -f buildozer-container
