name: Build Kivy App

on:
  push:
    branches:
      - master  # Use "main" if that is your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget unzip git
          pip install --upgrade pip
          pip install cython kivy buildozer

      - name: Set up Android SDK
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools" && cd "$ANDROID_HOME/cmdline-tools"
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
          unzip -o cmdline-tools.zip -d cmdline-tools
          mv cmdline-tools/* .
          rm -rf cmdline-tools
          yes | ./bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses
          yes | ./bin/sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-28" "build-tools;28.0.3" "platform-tools"
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk

      - name: Build the APK
        run: |
          export ANDROID_HOME=${{ github.workspace }}/android-sdk
          export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/build-tools/28.0.3:$PATH
          git --version
          buildozer android debug
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          PATH: ${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/cmdline-tools/bin:${{ github.workspace }}/android-sdk/build-tools/28.0.3:$PATH

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/*.apk
